import {
  Music,
  Trophy,
  Laugh,
  Palette,
  PartyPopper,
  Briefcase,
  DatabaseZap,
  Hotel,
  Shirt,
  HeartPlus,
} from "lucide-react";

export const categories = [
  {
    id: "music",
    name: "Music",
    icon: Music,
    description: "Concerts & Festivals",
    count: "2,500+ events",
    color: "bg-purple-500",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "sports",
    name: "Sports",
    icon: Trophy,
    description: "Games & Tournaments",
    count: "1,800+ events",
    color: "bg-green-500",
    gradient: "from-green-500 to-emerald-500",
  },
  {
    id: "comedy",
    name: "Comedy",
    icon: Laugh,
    description: "Stand-up & Shows",
    count: "850+ events",
    color: "bg-yellow-500",
    gradient: "from-yellow-500 to-orange-500",
  },
  {
    id: "arts",
    name: "Arts",
    icon: Palette,
    description: "Exhibitions & Galleries",
    count: "1,200+ events",
    color: "bg-blue-500",
    gradient: "from-blue-500 to-cyan-500",
  },

  {
    id: "nightlife",
    name: "Nightlife",
    icon: PartyPopper,
    description: "Clubs & Parties",
    count: "1,500+ events",
    color: "bg-indigo-500",
    gradient: "from-indigo-500 to-purple-500",
  },

  {
    id: "business",
    name: "Business",
    icon: Briefcase,
    description: "Conferences & Networking",
    count: "1,100+ events",
    color: "bg-slate-600",
    gradient: "from-slate-600 to-slate-700",
  },
  {
    id: "health",
    name: "Health & Wellness",
    icon: HeartPlus,
    description: "Yoga & Meditation",
    count: "720+ events",
    color: "bg-teal-500",
    gradient: "from-teal-500 to-cyan-500",
  },

  {
    id: "tech",
    name: "Tech",
    icon: DatabaseZap,
    description: "Tech event & Networking",
    count: "980+ events",
    color: "bg-fuchsia-500",
    gradient: "from-fuchsia-500 to-purple-500",
  },
  {
    id: "conference",
    name: "Conference",
    icon: Hotel,
    description: "Meetings & Discussion",
    count: "980+ events",
    color: "bg-fuchsia-500",
    gradient: "from-fuchsia-500 to-purple-500",
  },
  {
    id: "fashion",
    name: "Fashion",
    icon: Shirt,
    description: "Designing & Merchandiser",
    count: "980+ events",
    color: "bg-fuchsia-500",
    gradient: "from-fuchsia-500 to-purple-500",
  },
];
