import {
  Music,
  Trophy,
  Laugh,
  Palette,
  Utensils,
  Mic2,
  Theater,
  PartyPopper,
  Briefcase,
  Heart,
  Dumbbell,
  GraduationCap,
} from "lucide-react";

export const categories = [
  {
    id: "music",
    name: "Music",
    icon: Music,
    description: "Concerts & Festivals",
    count: "2,500+ events",
    color: "bg-purple-500",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    id: "sports",
    name: "Sports",
    icon: Trophy,
    description: "Games & Tournaments",
    count: "1,800+ events",
    color: "bg-green-500",
    gradient: "from-green-500 to-emerald-500",
  },
  {
    id: "comedy",
    name: "Comedy",
    icon: Laugh,
    description: "Stand-up & Shows",
    count: "850+ events",
    color: "bg-yellow-500",
    gradient: "from-yellow-500 to-orange-500",
  },
  {
    id: "arts",
    name: "Arts",
    icon: Palette,
    description: "Exhibitions & Galleries",
    count: "1,200+ events",
    color: "bg-blue-500",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    id: "food",
    name: "Food & Drink",
    icon: Utensils,
    description: "Tastings & Dining",
    count: "950+ events",
    color: "bg-red-500",
    gradient: "from-red-500 to-rose-500",
  },
  {
    id: "nightlife",
    name: "Nightlife",
    icon: PartyPopper,
    description: "Clubs & Parties",
    count: "1,500+ events",
    color: "bg-indigo-500",
    gradient: "from-indigo-500 to-purple-500",
  },
  {
    id: "theater",
    name: "Theater",
    icon: Theater,
    description: "Plays & Performances",
    count: "680+ events",
    color: "bg-pink-500",
    gradient: "from-pink-500 to-rose-500",
  },
  {
    id: "business",
    name: "Business",
    icon: Briefcase,
    description: "Conferences & Networking",
    count: "1,100+ events",
    color: "bg-slate-600",
    gradient: "from-slate-600 to-slate-700",
  },
  {
    id: "health",
    name: "Health & Wellness",
    icon: Heart,
    description: "Yoga & Meditation",
    count: "720+ events",
    color: "bg-teal-500",
    gradient: "from-teal-500 to-cyan-500",
  },
  {
    id: "fitness",
    name: "Fitness",
    icon: Dumbbell,
    description: "Workouts & Classes",
    count: "890+ events",
    color: "bg-orange-500",
    gradient: "from-orange-500 to-red-500",
  },
  {
    id: "education",
    name: "Education",
    icon: GraduationCap,
    description: "Workshops & Seminars",
    count: "1,350+ events",
    color: "bg-amber-500",
    gradient: "from-amber-500 to-yellow-500",
  },
  {
    id: "live",
    name: "Live Shows",
    icon: Mic2,
    description: "Performances & Acts",
    count: "980+ events",
    color: "bg-fuchsia-500",
    gradient: "from-fuchsia-500 to-purple-500",
  },
];
